# Generated by Django 5.2 on 2025-12-12 02:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('RESIDENTE', 'Residente'), ('SEGURIDAD', 'Seguridad'), ('MANTENIMIENTO', 'Mantenimiento')], default='RESIDENTE', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email_verificado', models.BooleanField(default=False)),
                ('encoding_facial', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UnidadResidencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_unidad', models.CharField(max_length=10, unique=True, verbose_name='Número de Unidad')),
                ('estado_ocupacion', models.CharField(choices=[('OCUPADA_PROPIETARIO', 'Ocupada por Propietario'), ('ALQUILADA', 'Alquilada'), ('VACANTE', 'Vacante')], default='VACANTE', max_length=25)),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('superficie_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Superficie (m²)')),
                ('dormitorios', models.IntegerField(blank=True, null=True)),
                ('banos', models.IntegerField(blank=True, null=True, verbose_name='Baños')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_propias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unidad Residencial',
                'verbose_name_plural': 'Unidades Residenciales',
                'ordering': ['numero_unidad'],
            },
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_residente', models.CharField(choices=[('PROPIETARIO_RESIDENTE', 'Propietario Residente'), ('INQUILINO', 'Inquilino'), ('FAMILIAR', 'Familiar'), ('AUTORIZADO', 'Autorizado')], max_length=25)),
                ('es_principal', models.BooleanField(default=False, help_text='Indica si es el propietario o inquilino principal')),
                ('fecha_ingreso', models.DateField(help_text='Fecha de ingreso')),
                ('fecha_salida', models.DateField(blank=True, help_text='Fecha de salida', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residencias', to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residentes', to='users.unidadresidencial')),
            ],
            options={
                'verbose_name': 'Residente',
                'verbose_name_plural': 'Residentes',
                'ordering': ['-es_principal', '-fecha_creacion'],
            },
        ),
    ]
