# Generated by Django 5.2 on 2025-12-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('plate_detected', models.CharField(blank=True, max_length=20, null=True)),
                ('visitor_photo', models.ImageField(blank=True, null=True, upload_to='visitors/')),
                ('access_type', models.CharField(choices=[('ENTRY', 'Entrada'), ('EXIT', 'Salida')], max_length=10)),
                ('detection_method', models.CharField(choices=[('FACIAL', 'Reconocimiento Facial'), ('MANUAL', 'Manual'), ('CARD', 'Tarjeta'), ('PLATE', 'Reconocimiento de Placa')], default='MANUAL', max_length=20)),
                ('is_resident', models.BooleanField(default=False)),
                ('visitor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('camera_type', models.CharField(choices=[('ENTRANCE', 'Entrada'), ('EXIT', 'Salida'), ('PARKING', 'Estacionamiento'), ('COMMON_AREA', 'Área Común'), ('RESTRICTED', 'Área Restringida')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('has_facial_recognition', models.BooleanField(default=False)),
                ('has_ocr', models.BooleanField(default=False)),
                ('has_anomaly_detection', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cámara',
                'verbose_name_plural': 'Cámaras',
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('incident_type', models.CharField(choices=[('UNAUTHORIZED_ACCESS', 'Acceso No Autorizado'), ('UNKNOWN_PERSON', 'Persona Desconocida'), ('SUSPICIOUS_BEHAVIOR', 'Comportamiento Sospechoso'), ('LOOSE_DOG', 'Perro Suelto'), ('DOG_WASTE', 'Perro haciendo necesidades'), ('WRONG_PARKING', 'Vehículo mal estacionado'), ('OTHER', 'Otro')], default='OTHER', max_length=30)),
                ('description', models.TextField()),
                ('evidence_image', models.ImageField(upload_to='incidents/')),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=20)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Incidente de Seguridad',
                'verbose_name_plural': 'Incidentes de Seguridad',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('is_authorized', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
    ]
